# Generated by Django 3.0 on 2022-05-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20220505_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('food_category', models.CharField(default='salad', max_length=300, verbose_name='category')),
            ],
        ),
    ]
